	DEPMAKES := ../../ArpSrc/FFont/Makefile \
				../../ArpSrc/BeExp/Makefile \
				../../ArpSrc/ArpCollections/Makefile \
				../../ArpSrc/ArpViewKernel/Makefile \
				../../ArpSrc/ArpKernel/Makefile \
				../../ArpSrc/ArpViews/Makefile \
				../../ArpSrc/ArpLayout/Makefile \
				../../ArpSrc/AmKernel/Makefile \
				../../ArpSrc/AmFilters/Makefile
	SUBMAKES := MakeAmPhraseTest1 MakeAmFilterTest1

include ../../makefiles/submakes
