	DEPMAKES := ../ArpSrc/AmKernel/Makefile
	SUBMAKES := ArpChorus.mak \
				ArpConsole.mak \
				ArpControllerLimiter.mak \
				ArpControllerMap.mak \
				ArpControllerRange.mak \
				ArpCopy.mak \
				ArpDan.mak \
				ArpDianne.mak \
				ArpDissolve.mak \
				ArpDuration.mak \
				ArpEatDuplicates.mak \
				ArpEcho.mak \
				ArpEric.mak \
				ArpErode.mak \
				ArpEventMap.mak \
				ArpInverse.mak \
				ArpKeyboardSplitter.mak \
				ArpMerge.mak \
				ArpMetronome.mak \
				ArpMotionControl.mak \
				ArpMotionSplitter.mak \
				ArpMonophobic.mak \
				ArpNote.mak \
				ArpOnKey.mak \
				ArpOscillator.mak \
				ArpPandemic.mak \
				ArpParticleDecay.mak \
				ArpPinkNoise.mak \
				ArpQuantize.mak \
				ArpReverse.mak \
				ArpRubberStamp.mak \
				ArpSelective.mak \
				ArpShortShift.mak \
				ArpTilTheEnd.mak \
				ArpTimeStretch.mak \
				ArpTranspose.mak \
				ArpUncertainChorus.mak \
				ArpUncertainShuttle.mak \
				ArpUnstack.mak \
				ArpUnquantize.mak \
				ArpVaccine.mak \
				ArpVelocityMap.mak \
				ArpVelocitySplitter.mak \
				ArpVelociTease.mak \
				ArpWipeOut.mak

include ../makefiles/submakes

clean::
	rm -rf add-ons
