	DEPMAKES := ../../ArpSrc/ArpCollections/Makefile ../../ArpSrc/ArpKernel/Makefile \
				../../ArpSrc/FFont/Makefile ../../ArpSrc/ArpLayout/Makefile
	SUBMAKES := MakeLayout

include ../../makefiles/submakes
