	DEPMAKES := ../ArpSrc/FFont/Makefile \
				../ArpSrc/BeExp/Makefile \
				../ArpSrc/ArpCollections/Makefile \
				../ArpSrc/ArpKernel/Makefile \
				../ArpSrc/ArpLayout/Makefile \
				../ArpSrc/ArpViews/Makefile \
				../ArpSrc/AmKernel/Makefile \
				../ArpSrc/AmStdFactory/Makefile \
				../ArpSrc/Sequitur/Makefile \
				../AmFilters/Makefile
	SUBMAKES := MakeApp

include ../makefiles/submakes
