
# Copyright (c)1999 by Angry Red Planet.
#
# This code is distributed under a modified form of the
# Artistic License.  A copy of this license should have
# been included with it; if this wasn't the case, the
# entire package can be obtained at
# <URL:http://www.angryredplanet.com/>.
#
# ----------------------------------------------------------------------
#
# ARP/ArpSrc/ArpTerminal/Makefile
#
# Build the ArpTerminal library.
#
# ----------------------------------------------------------------------
#
# Known Bugs
# ~~~~~~~~~~
#
# ----------------------------------------------------------------------
#
# To Do
# ~~~~~
#
# ----------------------------------------------------------------------
#
# History
# ~~~~~~~
#
# Feb 2, 1999:
#	First public release.
#
#

	ARPROOT		= ../..
	IMG_NAME	= ArpTerminal
	
include $(ARPROOT)/makefiles/library
