	DEPMAKES := ../../ArpSrc/FFont/Makefile \
				../../ArpSrc/BeExp/Makefile \
				../../ArpSrc/ArpCollections/Makefile \
				../../ArpSrc/ArpKernel/Makefile \
				../../ArpSrc/ArpLayout/Makefile \
				../../ArpSrc/ArpViews/Makefile
	SUBMAKES := MakeAmKernel

include ../../makefiles/submakes
